# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g2GHhuyU2xwfJfw2XQfau6RjZrRELnwW
"""

# Commented out IPython magic to ensure Python compatibility.
#importing basics libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df=pd.read_excel('/content/drive/MyDrive/dog-breed-identification (4)/flight_price.xlsx')
df.head()

df.info()

df['Airline'].unique()

import pandas as pd

df['Date_of_Journey']=pd.to_datetime(df['Date_of_Journey'],infer_datetime_format=True)

df.info()

df['Day']=df['Date_of_Journey'].dt.day
df['Month']=df['Date_of_Journey'].dt.month
df['Year']=df['Date_of_Journey'].dt.year

df.head()

df.drop('Date_of_Journey',axis=1,inplace=True)

df.head()

##Fetaure Engineering Process
df['Dept_Hour']=df['Dep_Time'].str.split(':').str[0]
df['Dept_Min']=df['Dep_Time'].str.split(':').str[1]
df.drop('Dep_Time',axis=1,inplace=True)

df.info()

df['Dept_Hour']=df['Dept_Hour'].astype(int)
df['Dept_Min']=df['Dept_Min'].astype(int)
df['Arrival_Time']=df['Arrival_Time'].apply(lambda x: x.split(' ')[0])
df['Arrival_hour']=df['Arrival_Time'].str.split(':').str[0]
df['Arrival_min']=df['Arrival_Time'].str.split(':').str[1]
df['Arrival_hour']=df['Arrival_hour'].astype(int)
df['Arrival_min']=df['Arrival_min'].astype(int)
df.drop('Arrival_Time',axis=1,inplace=True)
df.info()

df['Total_Stops'].unique()

df['Total_Stops'].value_counts()

df[df['Total_Stops'].isnull()]

df['Total_Stops']=df['Total_Stops'].map({'non-stop':0,'1 stop':1,'2 stops':2,'3 stops':3,'4 stops':4,'nan':1})
df.head()

df['duration_hour']=df['Duration'].str.split(' ').str[0].str.split('h').str[0]
df[df['duration_hour']=='5m']

df.drop(6474,axis=0,inplace=True)
df['duration_min']=df['Duration'].str.split(' ').str[1].str.split('m').str[0]
df['duration_min']=df['duration_min'].fillna(0)
# Drop Duration
df.drop('Duration',axis=1,inplace=True)
df['duration_hour']=df['duration_hour'].astype(int)
df['duration_min']=df['duration_min'].astype(int)
"Mahika Aery".split(" ")[0]

df.info()

df.Airline.unique()

df.head()

## traget guided ordinal

df.groupby('Airline')['Price'].mean().sort_values()

from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
ohe.fit_transform(df[['Airline']]).toarray()

## Replacing target guided ordinal encoding
def replace_airline_with_mean(df):
    mean_prices = df.groupby('Airline')['Price'].mean().sort_values()
    df['Airline'] = df['Airline'].apply(lambda x: mean_prices[x])
    return df

df = replace_airline_with_mean(df)
df.head()
#pd.DataFrame(ohe.fit_transform(df[['Airline']]).toarray(),columns=ohe.get_feature_names())